apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay to opt in to rules ConfigMap usage.
# Usage: kubectl apply -k deploy/kustomize/overlays/with-rules

bases:
  - ../../base

resources:
  - ../../base/configmap-rules.yaml

patchesStrategicMerge:
  - configmap-patch.yaml
